name: registro_elettronico
description: >-
  A beautiful and simple school register app for Spaggiari.
  Made by students.

version: 0.0.8-dev.1 

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Dependency Injection
  injector: ^1.0.8
  # Object comparison
  equatable: ^1.0.3
  # BloC
  flutter_bloc: ^3.2.0
  # Database
  moor_flutter: ^2.1.0
  # Api
  dio: ^3.0.8
  retrofit: ^1.2.0

  # Use svg icons in home
  flutter_svg: ^0.15.0
  # Launcher icon
  flutter_launcher_icons: ^0.7.4

  # for percentage
  percent_indicator: ^2.1.1+1
  # for files
  path_provider: ^1.5.1
  #open downloaded file
  open_file: ^3.0.1
  # notifications
  workmanager: ^0.2.0

  # expandable school material
  expandable: ^4.0.1
  # open urls for school material
  url_launcher: ^5.4.1
  # pick a grade
  numberpicker: ^1.1.0

  # download indicator
  liquid_progress_indicator: ^0.3.2
  tuple: ^1.0.3
  # advanced logging
  f_logs: ^1.2.2
  # email
  flutter_email_sender: ^2.2.2
  #flutter_mailer: ^0.4.2
  dartz: ^0.8.9
  flutter_webview_plugin: ^0.3.10+1
  #webview_flutter: ^0.3.19+4
  pull_to_refresh: ^1.5.8
  # check if user is conntected
  data_connection_checker: ^0.3.4
  liquid_swipe: ^1.3.1
  rxdart: ^0.23.1
  # chart in stats page
  flutter_circular_chart: ^0.1.0
  package_info: ^0.4.0+13
  screenshot: ^0.1.1
  # share screenshot
  esys_flutter_share: ^1.0.2
  # unicorndial: ^1.1.5
  flutter_colorpicker: ^0.2.6
  # date time picker
  # datetime_picker_formfield: ^1.0.0
  flutter_local_notifications: ^1.1.5+1

  # firebase
  firebase_core: ^0.4.3+3
  # analytics
  firebase_analytics: ^5.0.2
  # crashalitycs
  firebase_crashlytics: ^0.1.2+4

  # Storing user password
  shared_preferences: ^0.5.4+8
  flutter_secure_storage: ^3.3.1+1
  # random string for flutter secure storage key generator
  random_string: ^1.1.0
  # for date time
  intl: ^0.16.0
  # calendar in agenda page
  table_calendar: ^2.2.1

  fl_chart: ^0.7.0

  # indexed_list_view: ^1.0.8
  # flutter_swiper: ^1.1.6
  # align_positioned: ^1.2.5
  # flutter_speed_dial: ^1.2.5

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator: ^2.1.1
  json_serializable: ^3.2.3
  retrofit_generator: ^1.0.2+2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"

flutter:
  assets:
    - assets/icons/
    - assets/icons/subjects/
    - lang/en.json
    - lang/it.json
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.otf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Montserrat-Italic.otf
          style: italic
        - asset: assets/fonts/Montserrat-Light.otf
          weight: 200
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 300
