name: registro_elettronico
description: A beautiful and simple school register app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Dependency Injection
  injector: ^1.0.8
  # Object comparison
  equatable: ^1.0.1
  # BloC
  flutter_bloc: ^3.1.0
  # Database
  moor_flutter: ^2.0.0
  # Api
  dio: ^3.0.7
  retrofit: ^1.0.1+1
  # Use svg icons
  flutter_svg: ^0.15.0
  # Launcher icon
  flutter_launcher_icons: ^0.7.4
  # for percentage
  percent_indicator: ^2.1.1+1
  # for files
  path_provider: ^1.5.1
  #open downloaded file
  open_file: ^2.1.1
  # notifications
  workmanager: ^0.1.5
  flutter_local_notifications: ^0.8.4
  # expandable school material
  expandable: ^4.0.1
  # open urls for school material
  url_launcher: ^5.4.1
  # pick a grade
  numberpicker: ^1.1.0
  # random colors for timetable
  random_color: ^1.0.3
  # initial slideshow
  flutter_swiper: ^1.1.6
  # intro page aligment
  align_positioned: ^1.2.5
  # download indicator
  liquid_progress_indicator: ^0.3.2
  tuple: ^1.0.3
  # timetable
  flutter_staggered_grid_view: ^0.3.0
  # share dialog
  share: ^0.6.3+5
  # advanced logging
  f_logs: ^1.2.2
  # email
  flutter_email_sender: ^2.2.2
  #flutter_mailer: ^0.4.2
  dartz: ^0.8.9
  cookie_jar: ^1.0.1
  #flutter_webview_plugin: ^0.3.10+1
  webview_flutter: ^0.3.19+4

  # firebase
  firebase_core: ^0.4.3+1
  # analytics
  firebase_analytics: ^5.0.2
  # crashalitycs
  firebase_crashlytics: ^0.1.2+4

  # Storing user password
  shared_preferences: ^0.5.4+8
  flutter_secure_storage: ^3.3.1+1
  # random string for flutter secure storage key generator
  random_string: ^1.1.0
  # for date time
  intl: ^0.16.0
  # calendar in agenda page
  table_calendar: ^2.2.1

  fl_chart: ^0.6.0

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator: ^2.1.1
  json_serializable: ^3.2.3
  retrofit_generator: ^1.0.2+2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  assets:
    - assets/icons/
    - assets/icons/subjects/
    - lang/en.json
    - lang/it.json
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.otf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Montserrat-Italic.otf
          style: italic
        - asset: assets/fonts/Montserrat-Light.otf
          weight: 200
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 300
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
