name: registro_elettronico
description: >-
  A beautiful and simple school register app for Spaggiari.
  Made by students.

version: 1.0.1-alpha

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Dependency Injection
  injector:
  # Object comparison
  equatable: 
  # BloC
  flutter_bloc:
  # Database
  moor_flutter: ^2.1.1
  # Api
  dio:
  retrofit:
  auto_size_text:
  # firebase_messaging: ^6.0.9

  # Use svg icons in home
  flutter_svg:
  # Launcher icon
  flutter_launcher_icons:

  # for percentage
  percent_indicator:
  # for files
  path_provider:
  #open downloaded file
  open_file:
  # notifications
  workmanager:

  # expandable school material
  expandable:
  # open urls for school material
  url_launcher:
  # pick a grade
  numberpicker:

  # download indicator
  liquid_progress_indicator:
  tuple:
  # advanced logging
  f_logs:
  # email
  flutter_email_sender:
  #flutter_mailer: ^0.4.2
  dartz:
  flutter_webview_plugin:
  #webview_flutter: ^0.3.19+4
  pull_to_refresh:
  # check if user is conntected
  data_connection_checker:
  liquid_swipe:
  rxdart:
  # chart in stats page
  flutter_circular_chart:
  package_info:
  screenshot:
  # share screenshot
  esys_flutter_share:
  # unicorndial: ^1.1.5
  flutter_colorpicker:
  # date time picker
  # datetime_picker_formfield: ^1.0.0
  flutter_local_notifications:

  # firebase
  firebase_core:
  # analytics
  firebase_analytics:
  # crashalitycs
  firebase_crashlytics:

  # Storing user password
  shared_preferences:
  flutter_secure_storage:
  # random string for flutter secure storage key generator
  random_string:
  # for date time
  intl:
  # calendar in agenda page
  table_calendar:

  fl_chart:
  # indexed_list_view: ^1.0.8
  # flutter_swiper: ^1.1.6
  # align_positioned: ^1.2.5
  # flutter_speed_dial: ^1.2.5

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator: ^2.1.1
  json_serializable: ^3.2.3
  retrofit_generator: ^1.0.2+2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"

flutter:
  assets:
    - assets/icons/
    - assets/icons/subjects/
    - lang/en.json
    - lang/it.json
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.otf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Montserrat-Italic.otf
          style: italic
        - asset: assets/fonts/Montserrat-Light.otf
          weight: 200
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 300
